### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by dqprecisian** [hcsp/fix-add-function#238]
![image](https://user-images.githubusercontent.com/36305085/66490837-620d6980-eae4-11e9-9ac3-5e62a0039a0f.png)
我这里没有那个**修改代码**的小标签还有
**start a review**
选项，
这是怎么回事，请指教。
@blindpirate

**Comment by blindpirate** [comment]
已经合并的PR没有这些选项，只有处于open状态的PR才有。
